### PR TITLE
signup and login

### PR DESCRIPTION
**Pull request by Nkarnaud**
the login is build on the django auth module. the signup is build using the userCreationForm

to run the app user:
python manager runserver
this link will bring you to the home page:
http://127.0.0.1:8000/  from this home page you have a link to signup and login.

### CODE REVIEW

**Comment by KenanBek** [comment]
In general, it looks quite OK, especially for learning purposes.

BUT

For the further learning purposes, try to add the following items:
- flake8 for linting
- isort for sorting
- view tests for new views

**Comment by KenanBek** [comment]
Before commiting new messages, use linter and isort to check your part of source code.

**Comment by Nkarnaud** [comment]
Thanks for the advice. what do you mean by view tests for new views?

**Comment by KenanBek** [comment]
> Thanks for the advice. what do you mean by view tests for new views?

by views I mean Django views: [Django Docs - Django Views](https://docs.djangoproject.com/en/2.2/topics/http/views/)

by view tests I mean tests for Django views: [Django Docs - Testing our new view](https://docs.djangoproject.com/en/2.2/intro/tutorial05/#testing-our-new-view)

**Pull request closed without merging**
